import random
import pandas as pd

AR_templates = {
      "question": [
    "ما سبب ظهور {symptom} بعد {activity}؟",
    "هل {symptom} يرتبط بـ {condition}؟",
    "كيف يمكن تخفيف {symptom} خلال {time_period}؟",
    "هل {symptom} طبيعي بعد {event}؟",
    "متى يجب القلق بشأن {symptom}؟",
    "هل {symptom} قد يكون بسبب {emotion}؟",
    "لماذا أشعر بـ {symptom} أثناء {activity}؟",
    "هل هناك علاقة بين {symptom} و{food}؟",
    "ما أفضل علاج لـ {symptom} المزمن؟",
    "هل {symptom} يؤثر على {daily_task}؟",
    "هل {symptom} يزداد في {season}؟",
    "ما تفسير {symptom} المتكرر؟",
    "هل يمكن أن يسبب {symptom} مضاعفات في {body_part}؟",
    "هل هناك تمارين تساعد في تقليل {symptom}؟",
    "ما الفرق بين {symptom} و{similar_symptom}؟",
    "هل القلق يسبب {symptom}؟",
    "هل {symptom} يستدعي زيارة الطبيب؟",
    "هل يوجد دواء يخفف {symptom}؟",
    "هل {symptom} مرتبط بمشاكل في {organ}؟",
    "هل تغيرات الطقس تؤثر على {symptom}؟",
    "هل يجب تجنب {activity} بسبب {symptom}؟",
    "هل {symptom} من أعراض {condition}؟",
    "ما السبب الطبي لـ {symptom} في {time_of_day}؟",
    "هل {symptom} شائع عند من يعاني من {condition}؟",
    "ماذا أفعل عند حدوث {symptom} فجأة؟",
    "هل {symptom} بعد {procedure} طبيعي؟",
    "متى يكون {symptom} خطيرًا؟",
    "هل هناك علاقة بين {symptom} و{habit}؟",
    "هل {symptom} يؤثر على النوم؟",
    "هل تناول {medication} يسبب {symptom}؟",
    "هل {symptom} يزداد مع {physical_state}؟",
    "هل {symptom} له علاقة بـ {age_group}؟",
    "هل يجب القلق إذا استمر {symptom} لأكثر من {duration}؟",
    "هل {symptom} قد يتحسن مع {treatment}؟",
    "هل {symptom} يتأثر بوضعية الجسم؟",
    "ما علاقة {symptom} بـ {mental_state}؟",
    "هل تغير النظام الغذائي يساعد في تقليل {symptom}؟",
    "ما أسباب تكرار {symptom} كل {interval}؟",
    "هل {symptom} يظهر فقط مع {trigger}؟",
    "هل يمكن أن تكون الحساسية سببًا في {symptom}؟",
    "هل {symptom} ناتج عن {infection}؟",
    "هل {symptom} من علامات {medical_issue}؟",
    "هل {symptom} يمنع ممارسة {activity}؟",
    "هل {symptom} يستدعي تحاليل معينة؟",
    "ما تأثير {symptom} على {life_area}؟",
    "ما العوامل التي تزيد من {symptom}؟",
    "هل {symptom} يسبب الإرهاق؟",
    "ما علاقة {symptom} بالدورة الشهرية؟",
    "هل {symptom} يؤثر على التركيز؟",
    "هل التوتر يزيد {symptom}؟",
    "هل النوم السيئ يفاقم {symptom}؟",
    "هل {symptom} علامة على شيء أخطر؟",
    "هل {symptom} مرتبط بالهرمونات؟",
    "هل {symptom} يتطلب تدخلًا جراحيًا؟",
    "هل {symptom} مؤقت أم دائم؟",
    "هل {symptom} يتحسن مع الراحة؟",
    "هل يمكن الشفاء التام من {symptom}؟",
    "هل {symptom} يؤثر على القلب؟",
    "هل {symptom} يرافقه دائمًا {other_symptom}؟",
    "هل {symptom} دليل على خلل داخلي؟",
    "هل {symptom} ناتج عن ضعف في {organ}? ",
    "هل {symptom} يسبب صعوبة في {function}؟",
    "هل من الطبيعي أن يحدث {symptom} بعد {time_period}؟",
    "هل {symptom} مرتبط بالحالة النفسية؟",
    "هل {symptom} يؤثر على النشاط اليومي؟",
    "هل هناك تحاليل تظهر سبب {symptom}؟",
    "هل {symptom} يمنع أداء {task}؟",
    "هل {symptom} يحتاج إلى تصوير طبي؟",
    "هل {symptom} علامة على نقص {vitamin}؟",
    "هل {symptom} طبيعي مع تقدم العمر؟",
    "هل {symptom} يحتاج علاجًا طويلاً؟",
    "هل {symptom} قد يتحول لشيء أخطر؟",
    "هل {symptom} له علاقة بالأعصاب؟",
    "هل {symptom} يختلف من شخص لآخر؟",
    "هل تناول {substance} يزيد {symptom}؟",
    "هل {symptom} يتحسن بالرياضة؟",
    "هل يمكن تجاهل {symptom}؟",
    "هل يجب تغيير الروتين بسبب {symptom}؟",
    "هل {symptom} يستدعي إجازة من العمل؟",
    "هل {symptom} يؤثر على العلاقة الزوجية؟",
    "هل {symptom} يترافق مع تقلب المزاج؟",
    "هل {symptom} مرتبط بمشاكل في التنفس؟",
    "هل {symptom} شائع بين النساء؟",
    "هل {symptom} يحتاج لإعادة تقييم؟",
    "هل {symptom} يمنع قيادة السيارة؟",
    "هل {symptom} من آثار {treatment}؟",
    "هل {symptom} يتأثر بالنشاط الجسدي؟",
    "هل {symptom} ممكن يكون تحسسي؟",
    "هل {symptom} يشير إلى اضطراب عضوي؟",
    "هل {symptom} من أعراض نقص المناعة؟",
    "هل {symptom} له علاقة بتغيير الوزن؟",
    "هل {symptom} يزيد أثناء الجلوس؟",
    "هل {symptom} مرتبط بنقص النوم؟",
    "هل {symptom} يترافق مع صعوبات التفكير؟",
    "هل {symptom} يختلف من موسم لآخر؟",
    "هل {symptom} يؤثر على المزاج العام؟",
    "هل يمكن التحكم في {symptom}؟",
    "ما أسوأ ما قد يسببه {symptom}؟",
    "هل {symptom} يرافقه دائمًا ألم؟",
    "هل {symptom} يحتاج مراجعة طارئة؟"
  ],
  "short": [
    "أشعر بـ {symptom} مفاجئ.",
    "استيقظت اليوم مع {symptom}.",
    "لا أستطيع تجاهل {symptom}.",
    "أصبحت {symptom} متكررة.",
    "{symptom} يمنعني من {activity}.",
    "لا تفسير لـ {symptom} حتى الآن.",
    "يعوقني {symptom} يوميًا.",
    "تعبت من {symptom} المستمر.",
    "{symptom} يزيد في فترة {time_period}.",
    "أشعر بالإرهاق بسبب {symptom}.",
    "ظهور {symptom} بعد {event}.",
    "أشعر أن {symptom} غير طبيعي.",
    "{symptom} يسبب لي القلق.",
    "صعوبة في النوم بسبب {symptom}.",
    "لا أتحمل {symptom} أكثر.",
    "أشعر بـ {symptom} عند {activity}.",
    "بدأت ألاحظ {symptom} منذ {duration}.",
    "{symptom} يجعل حياتي صعبة.",
    "ظهرت {symptom} بدون سبب.",
    "{symptom} يعطلني عن عملي.",
    "ما زلت أعاني من {symptom}.",
    "أشعر بـ {symptom} أثناء الراحة.",
    "تزداد {symptom} مع {emotion}.",
    "{symptom} مستمرة طوال اليوم.",
    "أواجه صعوبة بسبب {symptom}.",
    "أشعر أن {symptom} يتفاقم.",
    "أحتاج لحل لـ {symptom}.",
    "أرهقني {symptom} جدًا.",
    "لا أستطيع ممارسة {activity} بسبب {symptom}.",
    "الراحة لا تفيد مع {symptom}.",
    "{symptom} يجعلني أتوتر.",
    "أشعر بـ {symptom} بعد الأكل.",
    "لا أقدر على التركيز بسبب {symptom}.",
    "{symptom} لا يتوقف.",
    "أشعر بـ {symptom} كل صباح.",
    "{symptom} يظهر فجأة.",
    "مزاجي يتأثر بـ {symptom}.",
    "بدأت أعاني من {symptom} منذ {event}.",
    "{symptom} يحرمني من النوم.",
    "ألاحظ {symptom} في أوقات معينة.",
    "كل يوم أستيقظ مع {symptom}.",
    "{symptom} يمنعني من الراحة.",
    "أحاول تجاهل {symptom} لكني لا أستطيع.",
    "{symptom} يجعلني أبتعد عن الناس.",
    "أحتاج وقتًا للتعامل مع {symptom}.",
    "أشعر أن {symptom} يسيطر على يومي.",
    "كل شيء يتأثر بـ {symptom}.",
    "{symptom} يتكرر دون سبب واضح.",
    "أشعر أن {symptom} يزداد.",
    "لا يمكنني شرح {symptom} جيدًا.",
    "{symptom} غير محتمل.",
    "{symptom} يزعجني أثناء العمل.",
    "{symptom} يجعل يومي مرهقًا.",
    "لا أستطيع أداء {daily_task} بسبب {symptom}.",
    "أخاف من عودة {symptom}.",
    "{symptom} يشعرني بالعجز.",
    "أشعر أن {symptom} ليس له حل.",
    "حياتي تغيرت بسبب {symptom}.",
    "كل شيء أصبح أصعب بسبب {symptom}.",
    "الطعام يزيد {symptom} لدي.",
    "{symptom} يظهر في ظروف معينة.",
    "{symptom} يتغير حسب مزاجي.",
    "{symptom} يظهر كل أسبوع.",
    "تزداد {symptom} مع التوتر.",
    "أشعر بـ {symptom} بعد التمرين.",
    "{symptom} يتكرر كل مساء.",
    "أصبح {symptom} يؤثر على عائلتي.",
    "أحيانًا أرتاح من {symptom} لفترة قصيرة.",
    "أحتاج للمساعدة مع {symptom}.",
    "بدأت أعاني من {symptom} بعد {event}.",
    "أشعر أن {symptom} يعزلني.",
    "{symptom} يجعلني أرتبك.",
    "لا أستطيع تحديد سبب {symptom}.",
    "كل مرة أشعر بـ {symptom}، أتوتر.",
    "تعبت من البحث عن حل لـ {symptom}.",
    "{symptom} أصبح مزمنًا.",
    "بدأت أعتاد على {symptom}.",
    "أشعر أن لا أحد يفهم {symptom}.",
    "أحاول التكيف مع {symptom}.",
    "{symptom} يجعلني أغير خططي.",
    "{symptom} لا يتبع نمطًا ثابتًا.",
    "{symptom} يصيبني في أسوأ الأوقات.",
    "أشعر بالعجز مع {symptom}.",
    "{symptom} يتداخل مع حياتي.",
    "حياتي اليومية تتأثر بـ {symptom}.",
    "{symptom} مستمر رغم العلاج.",
    "لا أملك السيطرة على {symptom}.",
    "كل أسبوع يظهر {symptom} فجأة.",
    "أشعر أنني لست بخير بسبب {symptom}.",
    "{symptom} يمنعني من النوم الجيد.",
    "ما زلت أبحث عن سبب لـ {symptom}.",
    "مزاجي يتغير مع {symptom}.",
    "كل محاولاتي فشلت مع {symptom}.",
    "تعبت من الشكوى من {symptom}.",
    "أعيش يومي مع {symptom}.",
    "أشعر أن {symptom} يتحكم فيّ.",
    "لا أستطيع تجاهل تأثير {symptom}.",
    "تأثرت علاقاتي بـ {symptom}.",
    "أخاف من استمرار {symptom}.",
    "لا أستطيع شرح ما يسببه {symptom}."
  ]
    ,
    "narrative": [
        "أعاني من {symptom} منذ {duration}.",
        "بدأت {symptom} بعد ما حصل {event}.",
        "التعامل مع {symptom} يوميًا أمر مرهق.",
        "بخاف من {symptom} بسبب {reason}.",
        "لما تجي {symptom}، ما بقدر أعمل {activity}.",
        "مضت {time_period} وأنا أواجه {symptom} بشكل مستمر.",
        "من يوم {event}، و{symptom} ما فارقتني.",
        "بحس بـ {symptom} كل ما أعمل {activity}.",
        "لاحظت إن {symptom} تجي كل {interval}.",
        "الأطباء لحد الآن ما قدروا يفسروا {symptom}.",
        "بدأت {symptom} لما صار عندي {condition}.",
        "تركت {activity} بسبب استمرار {symptom}.",
        "شكل {symptom} عندي مختلف عن الوصف الشائع.",
        "عيلتي صارت تقلق من {symptom} اللي عندي.",
        "بسبب {symptom}، ما عدت أقدر أعمل {function}.",
        "لما تستمر {symptom} لـ {duration}، بخاف جدًا.",
        "أول مرة حسّيت بـ {symptom} كانت في {month/year}.",
        "{symptom} غيّرت مجرى حياتي بالكامل.",
        "عايش بخوف دائم من نوبة {symptom} الجاية.",
        "{symptom} مسيطرة على {daily_life_area} بحياتي.",
        "ما بعرف إمتى ترجع {symptom}.",
        "كانت {symptom} بسيطة بالبداية، بس صارت شديدة.",
        "بواجه {symptom} من أيام {year}.",
        "{condition} اللي عندي هو سبب {symptom}.",
        "كل العلاجات ما نفعِت مع {symptom}.",
        "كل {time_of_day} بصارع {symptom}.",
        "{symptom} خربتلي {event} مهم.",
        "بعد {symptom}، بحس بـ {emotion}.",
        "تعلمت أتكيف مع {symptom} المستمرة.",
        "على مدار {duration}، صرت ألاحظ نمط في {symptom}.",
        "لسه متذكر أول مرة حسيت بـ {symptom}.",
        "{symptom} سببت لي مشاكل بعلاقاتي.",
        "حتى الفحوصات المتقدمة ما فسرت {symptom}.",
        "عندي {symptom} وكمان {condition}.",
        "{symptom} أثرت على {life_area} في حياتي.",
        "دايمًا تجي {symptom} وقت {specific_circumstance}.",
        "جربت كل شي، وما في شي نفع مع {symptom}.",
        "حتى المختصين مش قادرين يعرفوا سبب {symptom}.",
        "الجو البارد يزيد من {symptom}.",
        "{symptom} بلشت بعد {procedure}.",
        "لاحظت إن {symptom} زادت وقت {life_event}.",
        "ما في دواء خفف من {symptom}.",
        "ما بقدر أعمل {daily_task} بسبب {symptom}.",
        "كل ما تجي {symptom}، تجي معها {related_symptom}.",
        "بدأت أحس بـ {symptom} من لما كان عمري {age}.",
        "{symptom} بتسوء لما أتعرض لـ {factor}.",
        "حاسس إن أكلي بيأثر على {symptom}.",
        "أحيانًا {symptom} تختفي في ظروف معينة.",
        "كل شي تغير بعد {event} اللي سبب {symptom}.",
        "{symptom} أثرت على قدرتي في {life_responsibility}.",
        "جربت {intervention}، بس {symptom} لسه موجودة.",
        "{symptom} بتيجي وتروح بشكل مزعج.",
        "{symptom} بتزيد خلال {season}.",
        "الإحساس بـ {symptom} يشبه {sensation_description}.",
        "بعد التمرين، {symptom} بتزيد.",
        "من يوم ما غيرت {habit}، و{symptom} ظهرت.",
        "بسجل {symptom} يوميًا، وما في حد مهتم.",
        "{symptom} بتوصل لذروتها في {specific_time}.",
        "حاسس إن التوتر بيخلي {symptom} تسوء.",
        "{symptom} بتنتقل لمنطقة {body_part}.",
        "كل مرة أعمل {activity}، تجي {symptom}.",
        "{Trigger} دايمًا بيحرّض {symptom}.",
        "{symptom} عندي مختلفة عن باقي الناس.",
        "كثيرًا ما بتصير {symptom} مع {other_symptom}.",
        "خضعت لـ {treatment} وما في أي تحسن في {symptom}.",
        "وضعيّة جسمي بتأثر على {symptom}.",
        "ما عم بنام منيح بسبب {symptom}.",
        "حاسس إن {infection} هو سبب {symptom}.",
        "لما أتوتر، {symptom} بتزيد.",
        "حتى {therapy} ما أثرت على {symptom}.",
        "شغلي تأثر كثير بسبب {symptom}.",
        "{symptom} ما بتضل ثابتة، بتروح وبتجي.",
        "جربت {medication}، بس {symptom} ما راحت.",
        "البرد بيخلي {symptom} أسوأ.",
        "غيرت تماريني الرياضية بسبب {symptom}.",
        "لما آكل {food}، {symptom} بتزيد.",
        "{symptom} بتزيد خلال {menstrual_phase}.",
        "لاحظت إن {symptom} بس بتظهر وقت {type_of_activity}.",
        "أحيانًا الراحة بتساعد، وأحيانًا بتسوء {symptom}.",
        "تغيرات درجة الحرارة بتحفز {symptom}.",
        "أوقات الضغط النفسي بتزيد {symptom}.",
        "{symptom} ما إلها نمط واضح، بتختلف كل مرة.",
        "{symptom} أثرت على حالتي النفسية.",
        "لاحظت {symptom} لأول مرة بعد {injury}.",
        "موسم الحساسية بيزيد من {symptom}.",
        "وضعيّة جسمي مرتبطة بظهور {symptom}.",
        "صرت أعتذر عن التجمعات بسبب {symptom}.",
        "لما أجلس بـ {position}، {symptom} بتزيد.",
        "جربت {alternative_therapy}، وما تغير شي.",
        "لما أكون بأماكن مرتفعة، {symptom} بتسوء.",
        "كل جدولي اليومي تغير بسبب {symptom}.",
        "لما ما أشرب كفاية، {symptom} بتزيد.",
        "الأيام الماطرة بتكثف {symptom}.",
        "بعض الأدوية بتزيد من {symptom}.",
        "{symptom} سببت توتر في علاقاتي.",
        "حسب وضعية نومي، بحس بـ {symptom}.",
        "تغيّرات الهرمونات بتضخم {symptom}.",
        "شكل {symptom} مرتبط بعملية الهضم.",
        "{symptom} قللت من جودة حياتي.",
        "بتمنى ألاقي حل لـ {symptom} اللي مسببلي هالعذاب."
    ],
    "help": [
    "أحتاج مساعدة عاجلة بخصوص {symptom}",
    "هل من نصيحة بخصوص {symptom}؟",
    "أطلب توجيهًا طبيًا لـ {symptom} المستمر منذ {time}",
    "كيف يمكن إيقاف {symptom} أثناء {activity}؟",
    "ما التصرف السريع عند تفاقم {symptom}؟",
    "من الطبيب المناسب للتعامل مع {symptom} الشديد؟",
    "هل يجب الذهاب للمستشفى بسبب {symptom} مع {condition}؟",
    "ما أسرع وسيلة لتخفيف {symptom} الآن؟",
    "هل {symptom} من أعراض تستدعي الاتصال بالإسعاف؟",
    "كيفية التعامل مع نوبات {symptom} المزمنة؟",
    "لم أعد أحتمل هذا {symptom}، ماذا أفعل؟",
    "هل أطلب رأيًا ثانيًا بخصوص {symptom} المستمر؟",
    "ما الفحوصات الطارئة التي تكشف سبب {symptom}؟",
    "كيف أشرح أعراض {symptom} لطبيبي المختص؟",
    "هل توجد مجموعات دعم لمن يعاني من {symptom}؟",
    "ما الإجراءات إذا استمر {symptom} لـ {time}؟",
    "هل {symptom} أثناء {activity} يشكل خطرًا؟",
    "هل أزور الطوارئ أم أتابع مع عيادة لـ {symptom}؟",
    "كيف أقنع الأطباء بخطورة {symptom} عندي؟",
    "ما العلامات التي تدل أن {symptom} مهدد للحياة؟",
    "لا أستطيع متابعة حياتي بسبب {symptom}، أي حل؟",
    "أحتاج مشورة فورية حول نمط {symptom} عندي",
    "أي قسم في المستشفى يتعامل مع {symptom}؟",
    "كيف أحصل على مساعدة لـ {symptom} المتكرر؟",
    "ماذا أفعل عند ظهور {symptom} أثناء {circumstance}؟",
    "أي طبيب يجب مراجعته لـ {symptom}؟",
    "ما الحالات التي تستوجب الاتصال بالإسعاف لـ {symptom}؟",
    "ما العلاجات الفورية المتاحة لـ {symptom}؟",
    "كيف أصل إلى رعاية مناسبة لـ {symptom}؟",
    "هل التوجه للطوارئ ضروري في حالة {symptom}؟",
    "لا أستطيع النوم بسبب {symptom}، ماذا أفعل؟",
    "أحتاج إرشادات حول كيفية السيطرة على {symptom}",
    "متى يُعتبر {symptom} حالة طارئة؟",
    "كيف أطلب مساعدة لحالة {symptom} غير المفسرة؟",
    "ما أول إجراء عند ظهور {symptom} مع {condition}؟",
    "ما الفحوصات اللازمة لـ {symptom} المزمن؟",
    "طرق عاجلة لتخفيف {symptom}؟",
    "كيف أجعل الطبيب يهتم بـ {symptom}؟",
    "هل يوجد طوارئ لـ {symptom} الذي يحدث في {time}؟",
    "متى يستدعي {symptom} دخول المستشفى؟",
    "لا أستطيع العمل بسبب {symptom}، ماذا أفعل؟",
    "هل يمكن المساعدة في تحليل نمط {symptom}؟",
    "أي طبيب مختص يتابع حالات مثل {symptom}؟",
    "كيف أحصل على تقييم قلب عاجل؟",
    "ما الخطوات الطارئة لـ {symptom} الحاد؟",
    "ما الأدوية المفيدة في نوبات {symptom} المفاجئة؟",
    "هل يستدعي {symptom} مع {additional_symptom} الاتصال بالإسعاف؟",
    "ما الإجراءات التشخيصية السريعة لـ {symptom}؟",
    "كيف أحصل على رعاية عاجلة لـ {symptom}؟",
    "هل أنتظر أم أزور الطوارئ مع {symptom}؟",
    "لا أتنفس بشكل جيد أثناء {symptom}، ما العمل؟",
    "هل من نصيحة حول تكرار {symptom}؟",
    "متى يُعتبر {symptom} خطرًا؟",
    "كيف أطلب مساعدة لـ {symptom} في الليل؟",
    "ما التدخلات العاجلة الممكنة لـ {symptom}؟",
    "أي مستشفى تنصحون به لتشخيص {symptom}؟",
    "هل {symptom} أثناء الحمل طارئ؟",
    "كيف أصل إلى أخصائي قلب بسرعة؟",
    "ما التصرف في حالة {symptom} عند {patient_group}؟",
    "لا أستطيع القيام بمهامي بسبب {symptom}",
    "هل أطلب تقييمًا ثانيًا لسبب {symptom}؟",
    "متى يجب الاتصال بالإسعاف في حالة {symptom}؟",
    "كيف أتصرف عند تفاقم {symptom}؟",
    "ما أفضل طوارئ للتعامل مع أعراض قلبية مثل {symptom}؟",
    "هل {symptom} مع تغيرات {vital_sign} تستدعي تدخلًا فوريًا؟",
    "هل يجب فحص {symptom} فورًا؟",
    "كيف أُسرّع تشخيص {symptom}؟",
    "ما البروتوكول العاجل للتعامل مع {symptom} في المنزل؟",
    "لا أستطيع الاعتناء بأسرتي بسبب {symptom}",
    "كيف أدوّن {symptom} بطريقة تساعد الطبيب؟",
    "لمن أتوجه لتحويلي لطبيب متخصص في {symptom}؟",
    "كيف أطلب مراقبة قلبية مرتبطة بـ {symptom}؟",
    "ما أولويات التعامل مع تفاقم {symptom}؟",
    "ما الفحوصات المطلوبة فورًا لـ {symptom}؟",
    "متى أذهب للطوارئ إن استمر {symptom}؟",
    "كيف أحصل على موعد فحص {symptom} في نفس اليوم؟",
    "ماذا أفعل إن كنت أعاني من {symptom} مع {history}؟",
    "لا أستطيع إدارة يومي بسبب {symptom}",
    "ما مقياس شدة {symptom}؟",
    "كيف أعرف إذا كان {symptom} يتطور؟",
    "كيف أحصل على استشارة قلبية طارئة؟",
    "ما الطرق السريعة لتخفيف {symptom} المرهق؟",
    "أي قسم بالمستشفى مختص بـ {symptom}؟",
    "هل {symptom} مع وجود {family_history} يستوجب الطوارئ؟",
    "كيف أبدأ تشخيص عاجل لـ {symptom}؟",
    "ما أسهل طريقة لفحص {symptom} بسرعة؟",
    "ماذا أفعل عند حدوث أزمة {symptom}؟",
    "لم أعد أتحمل ألم {symptom}، أحتاج مساعدة",
    "كيف أتعامل مع النظام الصحي بخصوص {symptom}؟",
    "أي طبيب يتعامل مع حالات {symptom} المعقدة؟",
    "كيف أطلب علاج عاجل لـ {symptom}؟",
    "ما أول إجراء إن كنت أعاني من {symptom} ولدي {risk_factor}؟",
    "ما الفحوصات الطارئة لـ {symptom}؟",
    "ما معايير استدعاء الطوارئ لـ {symptom} عند {age_group}؟",
    "ما خيارات الرعاية العاجلة لـ {symptom} اليوم؟",
    "كيف أصل إلى خدمات طارئة للقلب؟",
    "ما التصرف عند ظهور {symptom} أثناء العمل؟",
    "لم أعد أستطيع تجاهل {symptom}",
    "أحتاج رأيًا سريعًا بخصوص {symptom}",
    "كيف أفرق إذا كان {symptom} متعلقًا بالقلب؟",
    "ماذا أفعل إذا كان {symptom} مقلقًا؟",
    "ما التصرف عند حدوث {symptom} بعد تناول {medication}؟",
    "أي أطباء يجب أن يتعاونوا في حالة {symptom}؟"
],
    
}

EN_templates ={
  "short": [
    "Sudden {symptom} feels alarming.",
    "I often wake up with {symptom}.",
    "{symptom} hits me after {activity}.",
    "Can't ignore this {symptom} anymore.",
    "My {symptom} worsens at {time}.",
    "What causes {symptom} like this?",
    "Felt {symptom} while doing {activity}.",
    "Strange {symptom} started after {event}.",
    "{symptom} is back again today.",
    "My {symptom} makes daily life hard.",
    "{symptom} usually follows {trigger}.",
    "Felt {symptom} while resting.",
    "This {symptom} is getting frequent.",
    "{symptom} disrupts my {daily_task}.",
    "Can’t focus because of {symptom}.",
    "Noticed {symptom} after {food}.",
    "I always get {symptom} during {activity}.",
    "My {symptom} is worse in {position}.",
    "{symptom} affects my routine.",
    "That sharp {symptom} came again.",
    "Random {symptom} without warning.",
    "Getting {symptom} more often now.",
    "{symptom} started out of nowhere.",
    "No relief from this {symptom}.",
    "Can't explain this {symptom}.",
    "I feel {emotion} because of {symptom}.",
    "Another day with {symptom}.",
    "{symptom} returns after {duration}.",
    "Unbearable {symptom} today.",
    "Still struggling with {symptom}.",
    "My {symptom} wakes me up.",
    "I noticed {symptom} during {event}.",
    "{symptom} flares up randomly.",
    "Hard to sleep due to {symptom}.",
    "{symptom} worsens after {meal}.",
    "I dread getting {symptom} again.",
    "Can't tell why {symptom} starts.",
    "{symptom} appears after {emotion}.",
    "My {symptom} doesn't go away.",
    "Getting anxious over {symptom}.",
    "Is {symptom} ever normal?",
    "{symptom} is really draining.",
    "{symptom} ruins my {event}.",
    "I'm tired of constant {symptom}.",
    "{symptom} doesn’t respond to {treatment}.",
    "I avoid {activity} because of {symptom}.",
    "Daily {symptom} is exhausting.",
    "This {symptom} keeps recurring.",
    "Feeling defeated by {symptom}.",
    "{symptom} is worse in the morning.",
    "How to handle {symptom}?",
    "{symptom} is back with intensity.",
    "Can't predict my {symptom} anymore.",
    "Felt {symptom} while commuting.",
    "My {symptom} got worse today.",
    "{symptom} won’t give me a break.",
    "{symptom} follows no clear pattern.",
    "Even resting doesn’t stop {symptom}.",
    "Getting frustrated with {symptom}.",
    "My {symptom} comes in waves.",
    "{symptom} right after stress.",
    "I experience {symptom} every {time}.",
    "Feeling helpless about {symptom}.",
    "Nothing helps with {symptom}.",
    "{symptom} strikes when I’m active.",
    "Not sure if {symptom} is serious.",
    "I’ve had {symptom} for {duration}.",
    "This {symptom} feels unusual.",
    "Constant {symptom} makes me anxious.",
    "Scared of what {symptom} might mean.",
    "{symptom} affects my energy levels.",
    "{symptom} keeps getting worse.",
    "My {symptom} makes life unpredictable.",
    "Avoiding plans because of {symptom}.",
    "I felt {symptom} during {emotion}.",
    "The {symptom} made me stop everything.",
    "I notice {symptom} at {specific_time}.",
    "{symptom} is interfering with my job.",
    "Confused by this {symptom}.",
    "Can't sleep well with {symptom}.",
    "{symptom} hits after long days.",
    "Nothing relieves this {symptom}.",
    "Is it normal to have {symptom} like this?",
    "{symptom} after {medical_condition}.",
    "Worrying about this strange {symptom}.",
    "My {symptom} is hard to describe.",
    "Tried ignoring {symptom}, didn’t help.",
    "{symptom} disrupts everything I do.",
    "I get {symptom} without warning.",
    "Painful {symptom} in the middle of {activity}.",
    "Still don’t know what causes {symptom}.",
    "This {symptom} started gradually.",
    "{symptom} makes even rest difficult.",
    "Feeling lost dealing with {symptom}.",
    "I wish {symptom} would stop.",
    "Getting {symptom} more than before.",
    "{symptom} makes me fear exertion.",
    "{symptom} flares at random times.",
    "Can’t find relief from {symptom}.",
    "{symptom} is affecting my mood."
  ],




    "question" : [
    "What could be causing my {symptom} lately?",
    "Is it normal to feel {symptom} after {activity}?",
    "How serious is {symptom} if it happens during {time}?",
    "Could {symptom} be linked to {condition}?",
    "Why does {symptom} worsen when I {action}?",
    "Should I be worried about {symptom} after {event}?",
    "What tests are best for diagnosing {symptom}?",
    "Does {symptom} always mean a heart issue?",
    "Why is my {symptom} getting worse at {time_of_day}?",
    "What kind of doctor should I see for {symptom}?",
    "Is {symptom} connected to stress or anxiety?",
    "Can diet changes improve {symptom}?",
    "What triggers might be behind {symptom}?",
    "Is {symptom} a sign of something life-threatening?",
    "Why does {symptom} return after {activity}?",
    "Could {symptom} mean an underlying condition?",
    "Should I get a second opinion about {symptom}?",
    "Can {symptom} happen with normal test results?",
    "When should I go to the ER for {symptom}?",
    "Is {symptom} typical in people with {medical_history}?",
    "Could {medication} be causing my {symptom}?",
    "Is there a connection between {symptom} and {coexisting_symptom}?",
    "Why is {symptom} only happening on {side_of_body}?",
    "What lifestyle changes help manage {symptom}?",
    "How do I know if {symptom} is getting worse?",
    "What can I expect during diagnosis for {symptom}?",
    "Is there a specific treatment plan for {symptom}?",
    "How do other people manage {symptom}?",
    "Why does {symptom} only happen during {specific_situation}?",
    "Could {symptom} be part of a larger issue?",
    "What long-term effects can result from {symptom}?",
    "Why does {symptom} occur after meals?",
    "Is {symptom} worse in certain weather conditions?",
    "Could allergies be behind my {symptom}?",
    "Does {symptom} mean I should stop exercising?",
    "What warning signs should I watch for with {symptom}?",
    "Is there a link between {symptom} and hormones?",
    "What role does sleep play in {symptom}?",
    "How long should {symptom} last before I seek help?",
    "Is it safe to wait before addressing {symptom}?",
    "What do others experience with {symptom} like mine?",
    "Does {symptom} affect heart function directly?",
    "Why does {symptom} occur more often during stress?",
    "Is there any over-the-counter relief for {symptom}?",
    "Why am I only now experiencing {symptom} at my age?",
    "Could my family history explain this {symptom}?",
    "What’s the difference between {symptom} and {similar_symptom}?",
    "Can I still work out while having {symptom}?",
    "How do I talk to my doctor about {symptom} clearly?"
    "Is {symptom} something that needs urgent care?",
    "Can {symptom} lead to permanent damage?",
    "Should I track {symptom} daily or weekly?",
    "Is {symptom} typical in people with {age_group}?",
    "Does caffeine worsen {symptom}?",
    "Can dehydration cause {symptom} like this?",
    "Could {symptom} be related to my posture?",
    "Is {symptom} expected during recovery from {procedure}?",
    "How can I explain {symptom} clearly to my physician?",
    "What questions should I ask about {symptom} during my appointment?",
    "Could {symptom} result from a vitamin deficiency?",
    "Are there non-medication ways to ease {symptom}?",
    "What’s the difference between {symptom} and side effects of {medication}?",
    "Is {symptom} more common in women/men?",
    "Why is my {symptom} different from typical cases?",
    "Could {symptom} be an autoimmune issue?",
    "How urgent is testing if I have {symptom} daily?",
    "Is it safe to drive while experiencing {symptom}?",
    "Does {symptom} get worse with certain foods?",
    "Can emotional distress cause {symptom} this severe?",
    "What role does sleep position play in {symptom}?",
    "Is it normal for {symptom} to come and go like this?",
    "Can physical therapy help with {symptom}?",
    "Why isn’t my medication helping with {symptom}?",
    "What labs or scans can reveal the source of {symptom}?",
    "Is {symptom} something a general doctor can manage?",
    "Should I ask for a referral due to my {symptom}?",
    "Why does {symptom} occur only at night?",
    "Is there a relation between {symptom} and hormonal changes?",
    "Can {symptom} be triggered by temperature shifts?",
    "Is {symptom} a sign that my condition is worsening?",
    "What’s the best way to monitor changes in {symptom}?",
    "Can I prevent {symptom} with lifestyle adjustments?",
    "Why am I still experiencing {symptom} despite treatment?",
    "Should I push for more testing about my {symptom}?",
    "Is it safe to wait before treating {symptom}?",
    "How does {symptom} differ between individuals?",
    "Why is {symptom} stronger after physical effort?",
    "Could {symptom} be caused by an infection?",
    "What red flags are associated with {symptom}?",
    "Does altitude affect {symptom} levels?",
    "Can allergies cause similar {symptom} sensations?",
    "Is there a specific condition linked to this {symptom} pattern?",
    "Should I keep a journal about my {symptom}?",
    "How can I prepare for a consult about {symptom}?",
    "Could {symptom} be a reaction to recent travel?",
    "Does {symptom} suggest nerve involvement?",
    "How common is {symptom} among people with {condition}?",
    "Could {symptom} be a delayed response to {event}?",
    "Can {symptom} occur without any physical cause?"
],

    "narrative" :[
    "I've been living with {symptom} for {duration}.",
     "My {symptom} started after {event}.",
     "Dealing with {symptom} daily is exhausting.",
     "I fear my {symptom} because of {reason}.",
     "When {symptom} hits, I can't do {activity}.",
     "It’s been {time_period} of relentless {symptom}.",
     "Ever since {event}, I’ve had this {symptom}.",
     "{symptom} during {activity} makes me panic.",
     "I’ve noticed {symptom} happens every {interval}.",
     "Doctors still can’t explain my {symptom}.",
     "My {symptom} began when I developed {condition}.",
     "I stopped {activity} due to constant {symptom}.",
     "The {symptom} I experience doesn’t match common descriptions.",
     "My family is growing concerned about my {symptom}.",
     "{symptom} has taken away my ability to {function}.",
     "Episodes of {symptom} lasting {duration} are terrifying.",
     "I first experienced {symptom} in {month/year}.",
     "This {symptom} completely changed my life.",
     "I now live in fear of my next {symptom} episode.",
     "{symptom} controls most of my {daily_life_area}.",
     "I never know when the {symptom} will return.",
     "What started as mild {symptom} is now severe.",
     "I’ve been dealing with {symptom} since {year}.",
     "My {condition} is what triggered the {symptom}.",
     "No treatment seems to work on my {symptom}.",
     "Every {time_of_day}, I fight against {symptom}.",
     "My {symptom} ruined an important {event}.",
     "{symptom} leaves me feeling {emotion}.",
     "I’ve learned to cope with constant {symptom}.",
     "Over {duration}, I’ve tracked a pattern in my {symptom}.",
     "I still remember my first experience of {symptom}.",
     "{symptom} has strained my relationships.",
     "Even advanced tests can't explain this {symptom}.",
     "I have {symptom} along with {condition}.",
     "This {symptom} has affected my {life_area}.",
     "{symptom} always appears during {specific_circumstance}.",
     "Nothing I try seems to manage the {symptom}.",
     "Even specialists can’t diagnose the root of my {symptom}.",
     "Weather changes seem to affect my {symptom}.",
     "The {symptom} began after my {procedure}.",
     "I noticed {symptom} worsening during {life_event}.",
     "No medication seems to ease this {symptom}.",
     "I can’t do {daily_task} because of the {symptom}.",
     "{symptom} is always accompanied by {related_symptom}.",
     "I began having {symptom} around age {age}.",
     "{symptom} gets worse when I experience {factor}.",
     "I think my diet influences my {symptom}.",
     "Sometimes, {symptom} vanishes under certain {condition}.",
     "Everything changed after {event} triggered my {symptom}.",
     "My {symptom} is interfering with my {life_responsibility}.",
     "I’ve tried {intervention}, but my {symptom} persists.",
     "The way my {symptom} comes and goes is unsettling.",
     "{symptom} flares up especially during {season}.",
     "The {symptom} I feel is like {sensation_description}.",
     "After exercising, my {symptom} intensifies.",
     "Ever since I changed my {habit}, {symptom} appeared.",
     "I log my {symptom}, but no one seems to care.",
     "My {symptom} peaks at {specific_time}.",
     "I believe stress worsens my {symptom}.",
     "The {symptom} spreads to my {body_part}.",
     "During {activity}, I always get {symptom}.",
     "{Trigger} always seems to provoke my {symptom}.",
     "My {symptom} is nothing like typical cases.",
     "I often get {symptom} along with {other_symptom}.",
     "I've undergone {treatment} without relief from {symptom}.",
     "My {symptom} changes based on body position.",
     "I barely sleep because of my {symptom}.",
     "I believe {infection} started my {symptom}.",
     "When I’m emotional, my {symptom} flares up.",
     "{Therapy} hasn’t touched my {symptom}.",
     "My job performance suffers because of {symptom}.",
     "{symptom} doesn’t stay constant—it comes in waves.",
     "I tried {medication}, but my {symptom} persisted.",
     "Cold weather makes my {symptom} worse.",
     "I had to change my workout due to {symptom}.",
     "After eating {food}, my {symptom} gets worse.",
     "My {symptom} worsens during {menstrual_phase}.",
     "I’ve noticed {symptom} only during {type_of_activity}.",
     "Rest sometimes helps, sometimes worsens {symptom}.",
     "My {symptom} gets triggered by temperature changes.",
     "Stressful times bring out the worst in my {symptom}.",
     "My {symptom} varies wildly—sometimes mild, sometimes awful.",
     "{symptom} has really affected my mental state.",
     "I started noticing {symptom} after my {injury}.",
     "Allergy season brings on a wave of {symptom}.",
     "My {symptom} is related to my posture.",
     "I miss out on social events due to {symptom}.",
     "{Position} always worsens my {symptom}.",
     "I tried {alternative_therapy}, but {symptom} stayed.",
     "Being at high altitudes makes my {symptom} worse.",
     "My daily schedule is now dictated by {symptom}.",
     "If I don’t drink enough, my {symptom} gets worse.",
     "Rainy days tend to intensify my {symptom}.",
     "Certain meds make my {symptom} flare up.",
     "My {symptom} puts a strain on relationships.",
     "I get {symptom} depending on how I sleep.",
     "Hormonal shifts really amplify my {symptom}.",
     "{symptom} seems tied to digestion somehow.",
     "Overall, my {symptom} has reduced my quality of life.",
     "I wish someone could help solve this {symptom} mystery."
],
  "help": [
    "Urgent help needed for {symptom}",
    "Please advise about my {symptom}",
    "Medical guidance needed for {symptom} lasting {time}",
    "How to stop {symptom} during {activity}?",
    "Emergency actions for worsening {symptom}",
    "Which specialist treats severe {symptom}?",
    "Hospital required for {symptom} with {condition}?",
    "Immediate relief options for {symptom}",
    "911 worthy {symptom} symptoms?",
    "Crisis management for chronic {symptom}",
    "Can't tolerate this {symptom} anymore",
    "Need second opinion about persistent {symptom}",
    "What ER tests identify cause of {symptom}?",
    "How to describe {symptom} to my cardiologist?",
    "Support groups for people with {symptom}?",
    "Emergency protocol when {symptom} lasts {time}",
    "Is this {symptom} during {activity} lethal?",
    "Urgent care or wait for {symptom} like this?",
    "How to convince doctors my {symptom} is real",
    "Life-threatening signs with {symptom}?",
    "Can't function with this {symptom}",
    "Need immediate advice about {symptom} pattern",
    "What hospital department handles {symptom}?",
    "How to get help for recurring {symptom}",
    "Emergency {symptom} during {circumstance}",
    "Which doctor specializes in {symptom}?",
    "911 call criteria for {symptom}?",
    "Urgent treatment options for {symptom}",
    "How to access care for persistent {symptom}",
    "Emergency room or clinic for {symptom}?",
    "Can't sleep due to {symptom}",
    "Need guidance on {symptom} management",
    "What constitutes {symptom} emergency?",
    "How to seek help for unexplained {symptom}",
    "Immediate steps for {symptom} with {condition}",
    "Which tests needed for chronic {symptom}?",
    "Emergency {symptom} relief methods?",
    "How to get doctors to take {symptom} seriously",
    "Urgent care for {symptom} during {time}?",
    "Hospital admission criteria for {symptom}?",
    "Can't work because of {symptom}",
    "Need help interpreting {symptom} pattern",
    "What specialist handles {symptom} cases?",
    "How to access urgent cardiac evaluation",
    "Emergency response for severe {symptom}",
    "Which medications help acute {symptom}?",
    "911 for {symptom} with {additional_symptom}?",
    "Urgent diagnostic options for {symptom}",
    "How to get priority care for {symptom}",
    "Emergency department or wait with {symptom}?",
    "Can't breathe properly during {symptom}",
    "Need advice on {symptom} frequency",
    "What indicates {symptom} is dangerous?",
    "How to get help for {symptom} at night",
    "Immediate interventions for {symptom}",
    "Which hospital best for {symptom} evaluation?",
    "Emergency {symptom} during pregnancy?",
    "How to access cardiac specialist quickly",
    "Urgent care for {symptom} in {patient_group}?",
    "Can't perform ADLs due to {symptom}",
    "Need second opinion on {symptom} cause",
    "What warrants ambulance for {symptom}?",
    "How to get emergency {symptom} relief",
    "Immediate steps for {symptom} progression",
    "Which ER is best for cardiac {symptom}?",
    "911 for {symptom} with {vital_sign} changes?",
    "Urgent evaluation for new {symptom}",
    "How to expedite {symptom} diagnosis",
    "Emergency protocol for {symptom} at home",
    "Can't care for family due to {symptom}",
    "Need help documenting {symptom} properly",
    "What specialist referrals for {symptom}?",
    "How to access cardiac monitoring for {symptom}",
    "Immediate actions for {symptom} flare-up",
    "Which tests urgently needed for {symptom}?",
    "Emergency department for {symptom} duration?",
    "How to get same-day {symptom} evaluation",
    "Urgent care for {symptom} with {history}?",
    "Can't manage daily life with {symptom}",
    "Need guidance on {symptom} severity scale",
    "What indicates {symptom} is progressing?",
    "How to get emergency cardiac consult",
    "Immediate relief for debilitating {symptom}",
    "Which hospital departments handle {symptom}?",
    "911 for {symptom} with {family_history}?",
    "Urgent diagnostic pathway for {symptom}",
    "How to access rapid {symptom} assessment",
    "Emergency measures for {symptom} crisis",
    "Can't tolerate {symptom} pain anymore",
    "Need help navigating {symptom} care system",
    "What specialist handles complex {symptom}?",
    "How to get urgent {symptom} treatment",
    "Immediate steps for {symptom} with {risk_factor}",
    "Which emergency tests for {symptom}?",
    "911 criteria for {symptom} in {age_group}?",
    "Urgent care options for {symptom} today",
    "How to access cardiac emergency services",
    "Emergency protocol for {symptom} at work",
    "Can't ignore {symptom} any longer",
    "Need immediate {symptom} triage advice",
    "What indicates {symptom} is cardiac?",
    "How to get help for alarming {symptom}",
    "Immediate actions for {symptom} with {medication}",
    "Which specialists collaborate on {symptom}?"
  ]
}




placeholders = {
    "symptom": [
        "صداع نصفي", "دوخة مستمرة", "فقدان التوازن", "خدر في الأطراف", "رعشة في اليدين",
        "زغللة في العين", "نوبات تشنج", "صعوبة في التركيز", "ثقل في الرأس",
        "طنين في الأذن", "تلعثم في الكلام", "تغيرات مزاجية", "فقدان مؤقت للذاكرة"
    ],
    "activity": [
        "القراءة", "الجلوس أمام الكمبيوتر", "القيادة لمسافة طويلة",
        "الانحناء للأمام", "القيام من النوم", "المشي في الشمس", "الوقوف لفترة طويلة"
    ],
    "function": [
        "التوازن", "الذاكرة", "التركيز", "الكلام", "السمع", "البصر", "التنفس أثناء النوم"
    ],
    "daily_task": [
        "التخطيط لليوم", "قيادة السيارة", "الكتابة", "العمل على الحاسوب", "التواصل مع الآخرين", "القراءة اليومية"
    ],
    "condition": [
        "الصرع", "الشلل النصفي", "السكتة الدماغية", "الصداع النصفي المزمن", "التصلب المتعدد", "التهاب الأعصاب", "اضطرابات النوم"
    ],
    "trigger": [
        "الضوء القوي", "قلة النوم", "الضغط العصبي", "الإرهاق الذهني", "الأصوات العالية"
    ],
    "position": [
        "الجلوس طويلاً", "الاستلقاء على الظهر", "الوقوف فجأة", "ثني الرقبة للأسفل"
    ],
    "treatment": [
        "الأدوية المضادة للتشنجات", "تمارين الذاكرة", "جلسات تخفيف التوتر", "أدوية الصداع النصفي", "جلسات علاج طبيعي عصبي"
    ],
    "emotion": [
        "القلق", "التشتت", "الارتباك", "الخوف", "الإرهاق العقلي", "الإحباط"
    ],
    "event": [
        "سقوط على الرأس", "نوبة صرع سابقة", "إجهاد في العمل", "موقف صادم", "حادث سير"
    ],
    "age_group": [
        "الأطفال", "الشباب", "كبار السن", "النساء بعد سن اليأس"
    ],
    "duration": [
        "بضع دقائق", "عدة ساعات", "يوم كامل", "أسابيع", "منذ شهور"
    ],
    "time": [
        "عند الاستيقاظ", "بعد الغداء", "في المساء", "خلال النوم", "عند التوتر"
    ],
    "weather": [
        "الحرارة العالية", "تغير الطقس", "الجو المغبر"
    ],
    "season": [
        "الربيع", "الصيف", "الخريف", "الشتاء"
    ],
    "food": [
        "الشكولاتة الداكنة", "القهوة", "الأجبان", "اللحوم المصنعة"
    ],
    "medication": [
        "دواء للصرع", "مسكن للصداع", "مهدئ أعصاب"
    ],
    "risk_factor": [
        "الضغط العالي", "التدخين", "قلة النوم", "القلق المزمن", "استخدام الشاشات لفترات طويلة"
    ],
    "mental_state": [
        "الارتباك", "النسيان المتكرر", "نوبات القلق", "الاكتئاب"
    ],
    "coexisting_condition": [
        "السكري", "الضغط المرتفع", "الاكتئاب", "مشاكل في النظر"
    ],
    "family_history": [
        "تاريخ عائلي مع الصرع", "إصابات دماغية وراثية", "وراثة السكتات الدماغية"
    ],
    "circumstance": [
        "أثناء القيادة", "بعد نقاش حاد", "بعد السهر الطويل", "أثناء الجلوس في ضوء ساطع",
        "خلال العمل تحت ضغط", "بعد تناول الكافيين", "بعد صدمة عاطفية", "عند الاستيقاظ المفاجئ"
    ]



}



english_placeholders = {
    "symptom": [
        "migraine headache", "chronic dizziness", "loss of balance", "numbness in limbs",
        "hand tremors", "blurred vision", "seizure episodes", "difficulty concentrating",
        "heavy head", "ear ringing", "slurred speech", "mood swings", "temporary memory loss"
    ],
    "activity": [
        "reading", "using a computer", "driving long distances",
        "bending forward", "getting out of bed", "walking in sunlight", "standing for a long time"
    ],
    "function": [
        "balance", "memory", "focus", "speech", "hearing", "vision", "breathing during sleep"
    ],
    "daily_task": [
        "planning the day", "driving", "writing", "working on a laptop", "communicating with others", "daily reading"
    ],
    "condition": [
        "epilepsy", "partial paralysis", "stroke", "chronic migraines", "multiple sclerosis",
        "nerve inflammation", "sleep disorders"
    ],
    "trigger": [
        "bright lights", "sleep deprivation", "mental stress", "mental fatigue", "loud noises"
    ],
    "position": [
        "sitting for long periods", "lying flat", "standing up suddenly", "neck bent downward"
    ],
    "treatment": [
        "anti-seizure medication", "memory exercises", "stress-relief therapy",
        "migraine medication", "neurological physiotherapy"
    ],
    "emotion": [
        "anxiety", "confusion", "nervousness", "fear", "mental exhaustion", "frustration"
    ],
    "event": [
        "head injury", "previous seizure", "work-related stress", "traumatic event", "car accident"
    ],
    "age_group": [
        "children", "young adults", "elderly", "postmenopausal women"
    ],
    "duration": [
        "a few minutes", "several hours", "an entire day", "weeks", "for months"
    ],
    "time": [
        "upon waking", "after lunch", "in the evening", "during sleep", "under stress"
    ],
    "weather": [
        "high heat", "changing weather", "dusty conditions"
    ],
    "season": [
        "spring", "summer", "autumn", "winter"
    ],
    "food": [
        "dark chocolate", "coffee", "cheese", "processed meats"
    ],
    "medication": [
        "epilepsy medication", "headache relief pills", "nerve relaxants"
    ],
    "risk_factor": [
        "high blood pressure", "smoking", "lack of sleep", "chronic stress", "excessive screen use"
    ],
    "mental_state": [
        "confusion", "frequent forgetfulness", "panic attacks", "depression"
    ],
    "coexisting_condition": [
        "diabetes", "hypertension", "depression", "vision problems"
    ],
    "family_history": [
        "family history of epilepsy", "inherited brain injuries", "stroke history in the family"
    ],
    "circumstance": [
        "while driving", "after a heated argument", "after staying up all night",
        "in bright lighting", "during work pressure", "after caffeine intake",
        "after an emotional shock", "on sudden awakening"
    ]
}






def generate_post(template, ph_dict):
    try:
        post = template.format(
            symptom=random.choice(ph_dict["symptom"]),
            activity=random.choice(ph_dict["activity"]) if "{activity}" in template else "",
            event=random.choice(ph_dict["event"]) if "{event}" in template else "",
            emotion=random.choice(ph_dict["emotion"]) if "{emotion}" in template else "",
            condition=random.choice(ph_dict["condition"]) if "{condition}" in template else "",
            time=random.choice(ph_dict["time"]) if "{time}" in template else "",
            circumstance=random.choice(ph_dict["circumstance"]) if "{circumstance}" in template else "",
            patient_group=random.choice(ph_dict["patient_group"]) if "{patient_group}" in template else "",
            history=random.choice(ph_dict["history"]) if "{history}" in template else "",
            risk_factor=random.choice(ph_dict["risk_factor"]) if "{risk_factor}" in template else "",
            vital_sign=random.choice(ph_dict["vital_sign"]) if "{vital_sign}" in template else "",
            family_history=random.choice(ph_dict["family_history"]) if "{family_history}" in template else "",
            medication=random.choice(ph_dict["medication"]) if "{medication}" in template else ""
        )
        return post
    except Exception as e:
        print(f"Template error: {e} | Template: {template}")
        return None

def generate_posts(templates, ph_dict, template_type_counts, used_posts):
    posts = []
    for template_type, template_list in templates.items():
        target_count = template_type_counts[template_type]
        current_count = 0
        attempts = 0
        max_attempts = 10000

        while current_count < target_count and attempts < max_attempts:
            template = random.choice(template_list)
            post = generate_post(template, ph_dict)
            if post and post not in used_posts:
                posts.append(post)
                used_posts.add(post)
                current_count += 1
                template_type_counts[template_type] -= 1
            attempts += 1

        if current_count < target_count:
            print(f"Warning: Only generated {current_count}/{target_count} posts for '{template_type}'")

    return posts

def main():
    used_arabic_posts = set()
    used_english_posts = set()

    template_type_counts_ar = {"short": 500, "question": 500, "narrative": 500, "help": 500}
    template_type_counts_en = {"short": 500, "question": 500, "narrative": 500, "help": 500}

    print("Generating Arabic posts...")
    arabic_posts = generate_posts(AR_templates, placeholders, 2000, template_type_counts_ar, used_arabic_posts)

    print("Generating English posts...")
    english_posts = generate_posts(EN_templates, english_placeholders, 2000, template_type_counts_en, used_english_posts)

    data = [{"post": post, "Tag": "Brain"} for post in arabic_posts + english_posts]

    df = pd.DataFrame(data)
    df.to_csv("d:FinalBrainposts.csv", index=False, encoding="utf-8")

    print(f"Done! {len(arabic_posts)} Arabic and {len(english_posts)} English posts saved")

if __name__ == "__main__":
    main()
